name: Build and Package NCMTool for Windows

on:
  push:
    branches: [main]
    tags: ['v*']
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout Source
        uses: actions/checkout@v3

      - name: Set up Qt
        uses: jurplel/install-qt-action@v3
        with:
          version: '6.5.0'
          arch: 'win64_msvc2019_64'
          tools: 'tools_windeployqt'

      - name: Install CMake
        uses: jwlawson/actions-setup-cmake@v1
        with:
          cmake-version: '3.27.0'

      - name: Install NSIS
        run: choco install nsis -y

      - name: Install UPX
        run: choco install upx -y

      - name: Add MSBuild to PATH
        uses: microsoft/setup-msbuild@v2

      - name: Build project
        run: ./build.bat

      - name: Create installer
        run: ./installer.bat

      - name: Upload Installer Artifact
        uses: actions/upload-artifact@v4
        with:
          name: ncmtool-installer
          path: |
            ncmtool_setup.exe

      - name: Publish GitHub Release (on tag)
        if: startsWith(github.ref, 'refs/tags/')
        uses: softprops/action-gh-release@v1
        with:
          name: Release ${{ github.ref_name }}
          tag_name: ${{ github.ref_name }}
          files: ncmtool_setup.exe
